#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
from datetime import datetime

from donkeycar.utilities.fira_autotune import (
    DEFAULT_BASELINE,
    format_overrides,
    load_reports,
    parse_sessions,
    run_autotune,
    summarize_report,
)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description='Offline autotuning for FIRA challenge parameters from session reports.',
    )
    parser.add_argument(
        '--reports-glob',
        default='data/**/fira_competition_report_*.json',
        help='Glob pattern for competition report JSON files.',
    )
    parser.add_argument('--output-dir', default='data/fira_autotune', help='Output directory.')
    parser.add_argument('--trials', type=int, default=80, help='Number of random-search trials.')
    parser.add_argument('--seed', type=int, default=42, help='Random seed for reproducibility.')
    parser.add_argument('--train-ratio', type=float, default=0.7, help='Train split ratio in [0,1].')
    parser.add_argument('--target-active-frames', type=int, default=120, help='Target active frames normalizer.')
    parser.add_argument(
        '--baseline-json',
        default=None,
        help='Optional JSON file with baseline overrides for tuned keys.',
    )
    return parser


def _load_baseline(path: str | None) -> dict:
    base = dict(DEFAULT_BASELINE)
    if not path:
        return base
    with open(path, 'r', encoding='utf-8') as f:
        user = json.load(f)
    if isinstance(user, dict):
        for key, value in user.items():
            if key in base:
                base[key] = value
    return base


def main() -> int:
    args = _build_parser().parse_args()

    payloads = load_reports(args.reports_glob)
    sessions = parse_sessions(payloads)
    if not sessions:
        print(f'No valid reports matched: {args.reports_glob}')
        return 1

    baseline = _load_baseline(args.baseline_json)
    report = run_autotune(
        sessions=sessions,
        baseline=baseline,
        trials=args.trials,
        seed=args.seed,
        train_ratio=args.train_ratio,
        target_active_frames=args.target_active_frames,
    )

    ts = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
    out_dir = args.output_dir
    os.makedirs(out_dir, exist_ok=True)
    report_path = os.path.join(out_dir, f'fira_autotune_report_{ts}.json')
    overrides_path = os.path.join(out_dir, f'fira_autotune_overrides_{ts}.py')

    with open(report_path, 'w', encoding='utf-8') as f:
        json.dump(report, f, indent=2, sort_keys=True)

    with open(overrides_path, 'w', encoding='utf-8') as f:
        f.write('# Auto-generated by scripts/fira_autotune.py\n')
        f.write(format_overrides(report['best']['params']))

    print(summarize_report(report))
    print(f'Wrote report: {report_path}')
    print(f'Wrote overrides: {overrides_path}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
